---
title: "Functions"
output: html_document
date: "2024-08-20"
---

Practice
```{r}

new_mean <- function() {
	n <- length(x)
	mean_val <- sum(x) / n
	return(mean_val)
}

x <- c(10,15,20,25,30)
n <- length(x)
mean_val <- sum(x)/n

new_mean <- function() {
	
	
}
```


#Square
```{r}
# start out with a number to test
x <- 3
# you'll want your function to return this number
x^2
square <- function(x) {
  sqvalue <- x*x
  return(sqvalue)
}
# test it out
square(x)
square(53)
53^2 # does this match?
```

```{r}
prop <- function(x) {
  n <- length(x)
  mean_val <- sum(x) / n
  return(mean_val)
}

#Lets test on a vector of 1s and 0s
x <- c(0, 1, 1)

#To calculate the proportion and turn it into a percentage, we’ll just multiply the mean by 100.
multiplier <- 100
multiplier * sum(x) / length(x)

#to return just proportion, we cna change multiplier to 1
multiplier <- 1
multiplier * sum(x) / length(x)

#Test again:
prop(x = c(1, 0, 1, 0), multiplier = 1)


#Since we don’t want users to have to specify multiplier = 1 every time they just want a proportion, we can set it as a default.

propo <- function(x, multiplier=1) {
  n <- length(x)
  proportion_val <- sum(x)/n
  multiplied_val <- multiplier * proportion_val
  return(multiplied_val)
}

x
n
proportion_val
  n <- length(x)
  proportion_val <- sum(x)/n
  multiplied_val <- multiplier * proportion_val
#Now we only need to specify that argument if we want a percentage.

#Default
propo(c(1,1,1,0,0))

propo(c(1,1,1,0,0), multiplier = 100)

raise(5)

raise(5, power =3)


```
Write a function to raise to any power. You don’t just want to square numbers, you want to raise them to higher powers too. Make a function that uses two arguments, x for a number, and power for the power. Call it raise().
```{r}

raise <- function(x, power = 2) {
	
	raisednum <- x^power
	return(raisednum)
  
}

# test with
raise(x = 2, power = 4)
# should give you
2^4

raise(x = x, power = 4)

```

NLSY DATA
```{r}
#| warning: false
#| message: false

library(tidyverse)
library(gtsummary)
nlsy_cols <- c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd", 
               "id", "nsibs", "samp", "race_eth", "sex", "region", 
               "income", "res_1980", "res_2002", "age_bir")
nlsy <- read_csv(here::here("data", "raw", "nlsy.csv"), 
                 na = c("-1", "-2", "-3", "-4", "-5", "-998"),
                 skip = 1, col_names = nlsy_cols) |> 
  mutate(region_cat = factor(region, labels = c("Northeast", "North Central", "South", "West")),
         sex_cat = factor(sex, labels = c("Male", "Female")),
         race_eth_cat = factor(race_eth, labels = c("Hispanic", "Black", "Non-Black, Non-Hispanic")),
         eyesight_cat = factor(eyesight, labels = c("Excellent", "Very good", "Good", "Fair", "Poor")),
         glasses_cat = factor(glasses, labels = c("No", "Yes"))) 


#Models

logistic_model <- glm(glasses ~ eyesight_cat + sex_cat,
  data = nlsy, family = binomial()
)

logbinomial_model <- glm(glasses ~ eyesight_cat + sex_cat,
  data = nlsy, family = binomial(link = "log")
)

poisson_model <- glm(nsibs ~ eyesight_cat + sex_cat,
  data = nlsy, family = poisson()
)


```




New Table Function

```{r}
new_table_function <- function(model, tidy_fun = broom.helpers::tidy_with_broom_or_parameters) {
  tbl_regression(
    model,
    exponentiate = TRUE,
     tidy_fun = tidyfun,
    label = list(
      sex_cat ~ "Sex",
      eyesight_cat ~ "Eyesight"
      
    )
  )
}

new_table_function(logistic_model,  tidy_fun = partial(tidy_robust, vcov = "HC1")) #not default tidyfun
new_table_function(logbinomial_model)
new_table_function(poisson_model)
```

